[package]
name = "marble_ray_tracer"
version = "0.1.0"
authors = ["Zac Gross <zac.a.gross@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
