[package]
name = "ray"
version = "0.1.0"
authors = ["Matt Harrison <hi@matt-harrison.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.12"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"